version: '2.4'

services:
    mongo:
      image: 'library/mongo:latest'
      restart: 'unless-stopped'
      networks:
        - default

    shorturl:
        image: 'samburney/url-shortener:latest'
        restart: 'unless-stopped'
        build: '.'
        ports:
          - '3000:3000'
        networks:
          - default

networks:
  default:
